version: "3"

services:
  web: &web
    build: .
    ports:
      - "${RUBY_PORT}:3000"
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    # env_file: .env
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_PORT: 5432
    volumes:
      - ./${PROJECT_NAME}:/app
      - bundle-volume:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  yarn:
    build:
      context: ./yarn
    volumes:
      - ./${PROJECT_NAME}:/app:cached
      - node-modules-volume:/app/node_modules
  mailhog:
    build:
      context: ./mailhog
    ports:
      - "${SMTP_PORT}:1025"
      - "${HTTP_PORT}:8025"
volumes:
  node-modules-volume:
  bundle-volume:
  postgres-data:
