version: "3"

services:
  web:
    build: web
    ports:
      - "${RUBY_PORT}:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=${POSTGRES_USER}"
      - "DATABASE_PASSWORD=${POSTGRES_PASSWORD}"
    links:
      - db
    volumes:
      - "./${PROJECT_NAME}:/app"
    stdin_open: true

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
