version: "3"

services:
  web:
    build: web
    ports:
      - "${RUBY_PORT}:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    links:
      - db
    volumes:
      - "./${PROJECT_NAME}:/app"
    stdin_open: true

  db:
    image: postgres:10.1
    ports:
      - "${DB_PORT}:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"